version: 2.1
jobs:
  zammad:
    docker:
      - image: zammad/zammad-ci:latest
        environment:
          PGHOST: '127.0.0.1'
          PGUSER: root
          RAILS_ENV: test
          Z_LOCALES: "en-us:de-de"
          REDIS_URL: redis://redis:6379
          ## Compile assets only once.
          CI_SKIP_ASSETS_PRECOMPILE: 'true'
          # Avoid unnecessary DB resets.
          CI_SKIP_DB_RESET: 'true'
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: zammad
          POSTGRES_PASSWORD: zammad
      - image: cimg/redis:5.0
      
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: node-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore Ruby Cache
          key: gems-v1{{ checksum "Gemfile.lock" }}
      - run: echo '127.0.0.1 redis postgresql' | sudo tee -a /etc/hosts
      - run: sudo apt update -y
      - run: sudo apt install -y postgresql-client
      - run: .github/workflows/ci/pre.sh
      - run: .github/workflows/ci/lint.sh        
      - run: .github/workflows/ci/test.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: node-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          name: Save Ruby Gems
          key: gems-v1{{ checksum "Gemfile.lock" }}          
          paths:
            - vendor
          
  CI-workflow:
    jobs:
      - zammad
