version: 2.1
jobs:
  zammad:
    docker:
      - image: zammad/zammad-ci:latest
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore Ruby Cache
          keys: cache-gems-{{ checksum "Gemfile.lock" }}
      - run: .github/workflows/ci/pre.sh
      - run: .github/workflows/ci/lint.sh        
      - run: .github/workflows/ci/test.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save Ruby Gems
          key: cache-gems-{{ checksum "Gemfile.lock" }}          
          paths:
            - ~/.bundle

workflows:
  CI-workflow:
    jobs:
      - zammad
